[package]
name = "api"
version = "0.1.0"
authors = ["Maniarr <nicolas@maniarr.fr>"]

[dependencies]
actix-web = "0.7"
env_logger = "0.5"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
reqwest = "0.9"
uuid = { version = "0.7", features = ["v4"] }
