version: '3'
services:
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - SWAGGER_JSON=/opt/swagger.yaml
    volumes:
      - $PWD/swagger.yaml:/opt/swagger.yaml
